### PR TITLE
Added suport to find first and last quarter of the moon

### PR DESCRIPTION
**Pull request by 1tchy**
I added suport to find first and last quarter of the moon and improved finding of moon events near and far from the given date. Feel free to include this as well.

### CODE REVIEW

**Comment by dustmachine** [comment]
I'm moving the ownership to a github "organization" for easier shared management and setup of Travis continuous integration.  Hopefully the transition is fairly seamless, https://github.com/SimpleAstronomy/simple-astronomy-lib

**Comment by damon140** [comment]
This pull request looks good, but I feel like I needed to write an overdue
test before I merge it.

I feel like I want  pseudo random number generated set of times set over a
couple of months, and a big pile of calculations for the full moon.

The pull request has a comment about an equal statement at the heart of the
binary search. It could be bug, and it is testable, so I'll make a test :)

d.

**Comment by 1tchy** [comment]
While waiting for your tests I've merged this with the newest version in your develop branch and added a fix for Julian date calculation for this leap year (2016).

**Comment by dustmachine** [comment]
closing because this content was contained within #15

**Pull request closed without merging**
